name: Compile master datadexes & push to build branch
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run compilation script
        run: |
          pip install commentjson
          python scripts/compile_masterdexes.py masterManifest.json

      - name: Commit to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Compiled changes from {sha}"
          SKIP_EMPTY_COMMITS: true